# Nikon D7200 at 720p

#==============#
# Camera Model #
#==============#

Camera:
  name: "Nikon D7200"
  setup: "monocular"
  model: "perspective"

  fx: 834.758364
  fy: 834.758364
  cx: 639.5
  cy: 359.5

  k1: -0.16665317
  k2: 0.169275353
  p1: 0.000682125
  p2: 0.000773939
  k3: -0.13336463

  fps: 30.0
  cols: 1280
  rows: 720

  color_order: "RGB"

#=====================#
# Tracking Parameters #
#=====================#

Preprocessing:
  min_size: 800

#================#
# ORB Parameters #
#================#

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.9
  num_covisibilities_for_landmark_generation: 20
  num_covisibilities_for_landmark_fusion: 20

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer:
  keyframe_size: 0.06
  keyframe_line_width: 1
  graph_line_width: 1
  point_size: 2
  camera_size: 0.07
  camera_line_width: 2
  viewpoint_x: 0
  viewpoint_y: -20
  viewpoint_z: -0.1
  viewpoint_f: 2800

#=========================#
# LoopDetector Parameters #
#=========================#

LoopDetector:
  enabled: true
  reject_by_graph_distance: true
  min_distance_on_graph: 50