# Logitech HD Webcam C270

#==============#
# Camera Model #
#==============#

Camera:
  name: "Logitech HD Webcam C270"
  setup: "monocular"
  model: "perspective"

  fx: 832.44
  fy: 832.44
  cx: 319.5
  cy: 239.5

  k1: -0.01672
  k2: 1.683981
  p1: 0
  p2: 0
  k3: -7.24369

  fps: 20.0
  cols: 640
  rows: 480

  color_order: "Gray"

#=====================#
# Tracking Parameters #
#=====================#

Preprocessing:
  min_size: 800

#================#
# ORB Parameters #
#================#

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.9
  num_covisibilities_for_landmark_generation: 20
  num_covisibilities_for_landmark_fusion: 20

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer:
  keyframe_size: 0.06
  keyframe_line_width: 1
  graph_line_width: 1
  point_size: 2
  camera_size: 0.07
  camera_line_width: 2
  viewpoint_x: 0
  viewpoint_y: -20
  viewpoint_z: -0.1
  viewpoint_f: 2800

#=========================#
# LoopDetector Parameters #
#=========================#

LoopDetector:
  enabled: true
  reject_by_graph_distance: true
  min_distance_on_graph: 50